In [3]:
import numpy as np

In [4]:
#Create a 1D array of numbers from 0 to 9
first_list = [1,2,3,4,5,6,7,8,9] #create list variable 

array = np.array([1,2,3,4,5,6,7,8,9]) #arrange into an array

print(first_list)          #print old and new variables 
print(array)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


In [6]:
#Create a 3×3 NumPy array of all Boolean value Trues
array_2 = np.array ([[3,3,3],[3,3,3],[3,3,3]])
array_3 = np.array ([3,3,3], dtype=bool) 
print(array_3)

[ True  True  True]


In [20]:
#Extract all odd numbers from array of 1-10
odd_num = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print (odd_num)

new_list = [x for x in odd_num if x % 2 == 1] #to get all  even numbers, change == 1 to == 0
print(new_list) 

# or use filter lambda method to get the same results e.g. by creating a list variable and then doing filter(lambda x:x % 2 ==1, list variable)

[ 1  2  3  4  5  6  7  8  9 10]
[1, 3, 5, 7, 9]


In [21]:
#Replace all odd numbers in an array of 1-10 with the value -1
replace_num = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

for x in range(len(replace_num)):
    if x % 2 != 1:
        replace_num[x] = -1
print(replace_num)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [31]:
#Convert a 1D array to a 2D array with 2 rows
Array_1D = np.ones (4)
print(Array_1D)
Array_2D = Array_1D.reshape(2, 2)
print(Array_2D)




[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [36]:
#Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals
a = np.arange(1,5).reshape(2,2)
b = np.arange(6,10).reshape(2,2)
print(a)
print(b)

c = np.dot(a, b)
print(c)

total_sum = np.sum(c)
print(total_sum)

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[22 25]
 [50 57]]
154


In [46]:
#Extension task 
array_4 = [1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3,]
a = [1,2,3,4,5]
b = [4,5,6,7,8,9]

#remove duplicates 
def remove_duplicates(duplist):
    noduplist = []
    for element in duplist:
        if element not in noduplist:
            noduplist.append (element)
    return noduplist
print(remove_duplicates(b))




[4, 5, 6, 7, 8, 9]
